import { isMobile } from "react-device-detect";

export const buttonBase = {
  padding: "10px 15px",
  borderRadius: "8px",
  fontSize: "14px",
  fontWeight: "600",
  cursor: "pointer",
  transition: "background-color 0.3s ease",
};

export const styles = {
  dashboard: {
    display: "flex",
    flexDirection: isMobile ? "column" : "row",
    minHeight: "100vh",
    backgroundColor: "#e9f2f7",
    borderRadius: "8px",
  },
  sidebar: {
    width: isMobile ? "100%" : "250px",
    backgroundColor: "#0c3446",
    color: "#fff",
    padding: isMobile ? "10px" : "20px",
    borderRadius: "8px",
  },
  sidebarTitle: {
    fontSize: isMobile ? "18px" : "22px",
    fontWeight: "bold",
    marginBottom: "20px",
    textAlign: "center",
  },
  welcomeMessage: {
    textAlign: "center",
    color: "#fff",
    marginBottom: "20px",
  },
  logoutButton: {
    backgroundColor: "#dc3545",
    color: "#fff",
    padding: "10px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    marginTop: "20px",
    transition: "background-color 0.3s",
  },
  navTabs: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  tab: {
    backgroundColor: "#bcd9e7",
    color: "#0c3446",
    padding: "10px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    transition: "background-color 0.3s",
  },
  activeTab: {
    backgroundColor: "#28a745",
    color: "#fff",
    padding: "10px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
  },
  content: {
    flex: 1,
    padding: "20px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "bold",
    marginBottom: "20px",
    color: "#18678d",
  },
  card: {
    backgroundColor: "#ffffff",
    padding: "20px",
    borderRadius: "15px",
    boxShadow: "0 10px 30px rgba(0, 0, 0, 0.1)",
    marginBottom: "30px",
    transition: "transform 0.3s, box-shadow 0.3s",
    ":hover": {
      transform: "translateY(-10px)",
      boxShadow: "0 15px 40px rgba(0, 0, 0, 0.2)",
    },
    color: "#333",
    fontFamily: "'Roboto', sans-serif",
  },
  cardTitle: {
    fontSize: "22px",
    fontWeight: "bold",
    marginBottom: "10px",
    color: "#0c3446",
  },
  cardDescription: {
    fontSize: "16px",
    marginBottom: "10px",
    color: "#0c3446",
  },
  cardDate: {
    fontSize: "14px",
    color: "#888",
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    marginTop: "15px",
  },
  approveButton: {
    ...buttonBase,
    backgroundColor: "#28a745",
    color: "#fff",
  },
  messageContainer: {
    padding: "20px",
    textAlign: "center",
    backgroundColor: "#ffe6e6",
    width: "50%",
    height: "200px",
    transform: "translateX(50%)",
    borderRadius: "10px",
    boxShadow: "0 0 10px rgba(0, 0, 0, 0.1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "red",
    fontSize: "18px",
  },
  message: {
    color: "#d9534f",
  },
  editButton: {
    ...buttonBase,
    backgroundColor: "#18678d",
    color: "#fff",
  },
  deleteButton: {
    ...buttonBase,
    backgroundColor: "#dc3545",
    color: "#fff",
  },
  inputField: {
    width: "100%",
    padding: "10px",
    marginBottom: "10px",
    borderRadius: "5px",
    border: "1px solid #ced4da",
  },
  saveButton: {
    backgroundColor: "#28a745",
    color: "#fff",
    padding: "10px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    marginRight: "10px",
  },
  cancelButton: {
    backgroundColor: "#dc3545",
    color: "#fff",
    padding: "10px",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
  },
  modalStyles: {
    content: {
      top: "50%",
      left: "50%",
      right: "auto",
      bottom: "auto",
      marginRight: "-50%",
      transform: "translate(-50%, -50%)",
      padding: "20px",
      borderRadius: "10px",
      width: "400px",
      maxWidth: "90%",
      maxHeight: "80vh",
      overflowY: "scroll",
    },
  },
  container: {
    fontFamily: "Arial, sans-serif",
  },
  articlesCount: {
    marginBottom: "10px",
  },
  filterContainer: {
    marginBottom: "20px",
    display: "flex",
    alignItems: "center",
  },
  label: {
    marginRight: "10px",
    fontWeight: "bold",
  },
  select: {
    padding: "5px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    color: "black",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "10px",
    overflowX: "auto",
    whiteSpace: "wrap",
  },
  th: {
    backgroundColor: "#fff",
    padding: "10px",
    border: "1px solid #ddd",
    textAlign: "left",
    fontSize: isMobile ? "12px" : "16px",
  },
  td: {
    padding: "10px",
    border: "1px solid #ddd",
    fontSize: isMobile ? "12px" : "16px",
  },
};
